### ISSUE TITLE
Hash Pricing view for All.

### ISSUE THREAD

**Issue by mhellwinkel** [provenance-io/provenance-mobile-wallet#203]
## Summary

Add the Hash Pricing View for Users who don't hold any assets.
<img width="328" alt="image" src="https://user-images.githubusercontent.com/12415321/167442106-ae9e516a-d796-447e-a753-ba9d0a2dda55.png">

## Problem Definition
Currently if you create a brand new wallet, your Portfolio view is sorta just blank. 
<img width="379" alt="image" src="https://user-images.githubusercontent.com/12415321/167442533-af14b7de-5619-415c-991a-f8248dd8d368.png">

## Proposal

I suggest to add the pricing view to this page for All cases, or at least for those with zero Assets, as I think this could help drive interest into the utility token for those who are not aware. Provenance benefits from this as a marketing tactic for hash as near term solution until a more robust 'get Hash' feature can be implemented into the wallet App.
<img width="379" alt="image" src="https://user-images.githubusercontent.com/12415321/167443127-4c228478-7d27-4ac5-af29-ecf33ec2ee13.png">
____

#### For Admin Use

- [x] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by jakegraves-figure** [comment]
@mhellwinkel @jdfigure So, display a value (even if $0.00) and clicking on that portfolio value sends you to the Hash Pricing View?

**Comment by jakegraves-figure** [comment]
The latest pull request adds an asset for Hash with an amount of `0` if there are no assets in the account.

If you have no Portfolio Balance when the assets are finished loading, the balance will be reflected as `$0.00`.

Some other fixes were made to the graph, to make it look more like the design.
